config/routes.rb
Rails.application.routes.draw do

  root 'welcome#index'

  devise_for :users, controllers: { registrations: 'registrations', omniauth_callbacks: 'omniauth_callbacks' }

  get 'courses/:id/terms/:term_number', to: 'courses#show', as: "show_term"
  put 'courses/:id/terms/new', to: 'courses#add_term', as: "add_term"
  get 'courses/:id/statistics', to: 'courses#statistics', as: "show_statistics"
  put 'courses/:id/terms/delete_last', to: 'courses#delete_term', as: "delete_term"
  # GitHub Authorization callback
  get 'github/callback'
  # Webhooks url
  post 'github/payload'

  resources :courses
  resources :students
  resources :homeworks

  resources :invitations, only: [ :new, :create, :edit, :update ]
  resources :tasks, only: [ :show, :update ] { member { get 'switch_chat' } }

  resources :messages
  
  resources :submissions, only: [ :new, :create, :index, :update ]
  resources :problems, only: [ :show ]
  resources :notes
  resources :links
  resources :notifications, only: [:update]
end

app/models/note.rb
class Note < ActiveRecord::Base
	validates :text, :submission_id, presence: true
	belongs_to :submission
end

app/controllers/notes_controller.rb
class NotesController < ApplicationController
  before_action :set_note, only: [ :update, :destroy ]
  respond_to :js

  def create
    @note = Note.new(notes_params)
    submission = @note.submission
    unless submission.notes.any?
      UserMailer.new_notes_notify(submission).deliver 
    end

    submission.task.accepted_partially!
    @note.save
    Notification.new_event(task: submission.task, user: submission.student.user, event_type: :added_comments, event_time: @note.created_at)
  end

  def update
    @note.update(notes_params)
  end

  def destroy
    @task = @note.submission.task
    @note.destroy
    Notification.comment_deleted(task: @task, user: @task.user)
    unless @task.notes.any?
      @task.new_submission!
    end
  end

  private
    def notes_params
      params.require(:note).permit(:text, :submission_id, :fixed)
    end

    def set_note
      @note = Note.find(params[:id])
    end
end

app/helpers/notes_helper.rb
module NotesHelper
end

app/views/notes/_note.html.erb
<h5 id="note_<%= note.id %>">
  <% if note.fixed? %>
    <span class="glyphicon glyphicon-ok"></span>
  <% else %>
    <span class="glyphicon glyphicon-exclamation-sign"></span>
  <% end %>

  <span class="markdown"><%= note.text.gsub("\n", "<br />").html_safe %></span>
  <small><strong><%= "v.#{note.submission.version}" %></strong><%=", #{note.created_at.strftime("%H:%M %d.%m.%y")}" %></small>

  <% if signed_in? && current_user.teacher? %>
    <% if not note.fixed? %>
      <%= link_to note_path(note, note: { fixed: true }), method: :put, title: "Принять", remote: true do %>
        <span class="glyphicon glyphicon-ok"></span>
      <% end %>
    <% else %>
      <%= link_to note_path(note, note: { fixed: false }), method: :put, title: "Отменить", remote: true do %>
        <span class="glyphicon glyphicon-remove"></span>
      <% end %>
    <% end %>

    <%= link_to note_path(note), method: :delete, remote: true do %>
      <span class="glyphicon glyphicon-trash"></span>
    <% end %>
  <% end %>

</h5>

app/views/notes/create.js.erb
$('#notes').show();
$('#notes').append('<%= j render(@note) %>');
$('#new_note #note_text').val('');
$('#new_note #submit_button').attr('disabled', true);

<% if @note.submission.task.notes.count == 1 %>
  $('#task_title #text').prepend('<span class="glyphicon glyphicon-exclamation-sign"></span>');
<% end %>

app/views/notes/destroy.js.erb
$('#note_<%= @note.id %>').remove();

<% if @task.new_submission? %>
  $('#task_title #text').replaceWith('<div id="text"> Задача <%= j @task.name %></div>')
<% end %>

app/views/notes/update.js.erb
$('#note_<%= @note.id %>').replaceWith('<%= j render(@note) %>');