config/routes.rb
Rails.application.routes.draw do

  root 'welcome#index'

  devise_for :users, controllers: { registrations: 'registrations', omniauth_callbacks: 'omniauth_callbacks' }

  get 'courses/:id/terms/:term_number', to: 'courses#show', as: "show_term"
  put 'courses/:id/terms/new', to: 'courses#add_term', as: "add_term"
  get 'courses/:id/statistics', to: 'courses#statistics', as: "show_statistics"
  put 'courses/:id/terms/delete_last', to: 'courses#delete_term', as: "delete_term"
  # GitHub Authorization callback
  get 'github/callback'
  # Webhooks url
  post 'github/payload'

  resources :courses
  resources :students
  resources :homeworks

  resources :invitations, only: [ :new, :create, :edit, :update ]
  resources :tasks, only: [ :show, :update ] { member { get 'switch_chat' } }

  resources :messages
  
  resources :submissions, only: [ :new, :create, :index, :update ]
  resources :problems, only: [ :show ]
  resources :notes
  resources :links
  resources :notifications, only: [:update]
end

app/models/task.rb
class Task < ActiveRecord::Base
  belongs_to :problem
  belongs_to :job
  belongs_to :student
  belongs_to :user

  counter_culture :student,
    :column_name => Proc.new {|model| !model.accepted? ? 'tasks_left_count' : nil },
    :column_names => { ["NOT tasks.status = ?", 3] => 'tasks_left_count' } # accepted status equals 3

  has_many :notifications, dependent: :destroy
  has_many :submissions, dependent: :destroy
  has_many :notes, through: :submissions

  scope :accepted, -> { where(status: self.statuses[:accepted]) }
  scope :without_notes, -> { includes(:notes).where(notes: { id: nil }) } 

  #chat
  has_many :messages, dependent: :destroy

  enum status: [ :not_submitted, :new_submission, :accepted_partially, :accepted, :new_submission_with_notes ]

  accepts_nested_attributes_for :submissions, :reject_if => :all_blank, :allow_destroy => true

  after_save :accept_notes, if: :accepted?
  after_save :update_job


  def name
    problem.get_name
  end

  def notes_count
    self.notes.count
  end

  def submissions_count
    self.submissions.count
  end

  private
    def accept_notes
      self.notes.each{ |note| note.update fixed: true }
    end

    def update_job
      @job = self.job
      @job.update(done: @job.tasks.select{|x| x.status != "accepted"}.empty?)
      if @job.done?
        if @job.assignment.awards.count < 3 && @job.assignment.assignment_type != "test"
          @job.awards.create(rank: @job.assignment.awards.count + 1)
        end
        assignment = @job.assignment
        if assignment.jobs.where(done: false).empty?
          assignment.update(done: true)
        end
      else
        @job.assignment.update(done: false)
        if @job.awards.count > 0
          @job.awards.first.destroy
        end
      end
    end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  include Markdown
  include FormHintHelper
  helper_method :markdown, :form_hint_for
  before_action :set_task, only: [ :show, :update, :switch_chat]

  def show
    if (not signed_in?)
      authenticate_user!
    end

    session[:task_url] = "/tasks/" + @task.id.to_s
    @course = @task.problem.homework.term.course

    @is_teacher = current_user == @course.teacher
    @is_student = current_user == @task.user

    if @is_student || @is_teacher || current_user.admin?
      @student     = @task.student
      @submissions = @task.submissions #reverse order
      @submission  = @submissions.first
    else
      raise ActionController::RoutingError.new('Not Found')
    end

    if @is_teacher && @submission
      Notification.make_read(user: @submission.teacher, task: @task)
    elsif @is_student
      Notification.make_read(user: @student.user, task: @task)
    end

    @is_chat_shown = @task.messages.count > 0
    @chat_button_title = @is_chat_shown ? 'Скрыть чат' : 'Показать чат'
  end

  def update
  	@task.update(params.require(:task).permit(:status))
    @task.touch
    if (params[:task][:status] == "accepted")
      event_type = :task_accepted
    else
      event_type = :task_accepted_partially
    end
    Notification.new_event(task: @task, user: @task.user, event_type: event_type, event_time: @task.updated_at)

    UserMailer.task_accepted_notify(@task).deliver if @task.accepted?

  	redirect_to @task
  end

  private
    def set_task
      @task = Task.find(params[:id])
    end

    def switch_chat
    end
end

app/helpers/tasks_helper.rb
module TasksHelper
  def after_cancel_status(task)
    if task.notes.any?
      "accepted_partially"
    elsif task.submissions.any?
      "new_submission"
    else
      "not_submitted"
    end
  end

  def idTypeOfSubmissionInEnum(type)
    case (type)
    when "Shift+Enter"
      return 0;
    when "Ctrl+Enter"
      return 1;
    when "Enter"
      return 2;
    end
  end
end

app/views/tasks/_chat.html.erb
<div class="container" id="chat-table">
  <h1 class="page-header">Обсуждение </h1>
  <%= render partial: 'message', collection: @task.messages %>
  <div class="row" id="form-row">
    <div class="col-sm-1">
      <div class="thumbnail">
        <%= gravatar_for current_user %>
      </div>
    </div>
    <div class="col-sm-6">
        <%= render 'new_message_form' %>
    </div>
  </div>
</div>

app/views/tasks/_markdown_help_model.html.erb
<div class="modal-header">
  <button type="button" class="close" data-dismiss="modal" aria-label="Close">
    <span aria-hidden="true">&times;</span>
  </button>
  <h1 class="modal-title" id="MarkdownLabel">Синтаксис Markdown</h4>
</div>

<div class="modal-body">
  <table class="table table-striped">
   <thead>
     <tr>
       <th><h3>Результат</h3></th>
       <th><h3>Markdown</h3></th>
     </tr>
   </thead>
   <tbody>
     <tr>
       <td><strong>Жирный</strong></td>
       <td>**Текст**</td>
     </tr>
     <tr>
       <td><em>Курсив</em></td>
       <td>*Текст*</td>
     </tr>
     <tr>
       <td><a>Ссылка</a></td>
       <td>[Описание](httl://)</td>
     </tr>
     <tr>
       <td><code>Код</code></td>
       <td>`код`</td>
     </tr>
     <tr>
       <td>H1</td>
       <td># Заголовок</td>
     </tr>
     <tr>
       <td>H2</td>
       <td>## Заголовок</td>
     </tr>
     <tr>
       <td>H3</td>
       <td>### Заголовок</td>
     </tr>
     <tr>
       <td><ul><li>Маркированный список</li></ol></td>
       <td>Три пробела + * + пробел</td>
     </tr>
     <tr>
       <td><ol><li>Нумерованный список</li></ol></td>
       <td>Три пробела + 1. + пробел</td>
     </tr>
   </tbody>
 </table>
</div>

<div class="modal-footer">
  <button type="button" class="btn btn-secondary" data-dismiss="modal">Закрыть</button>
</div>

app/views/tasks/_message.html.erb
<div class="row">
  <div class="col-sm-1 <% if message.user != current_user%> pull-right <% end %> ">
    <div class="thumbnail">
      <%= gravatar_for message.user %>
    </div>
  </div>
  <div class="col-sm-6<% if message.user != current_user%> pull-right <% end %> ">
    <div class="panel message-panel panel-default">
      <div class="<%= "panel-heading #{message.user != current_user ? "right" :
                 "left"}-arrow".squish %>">
        <strong><%=message.user.full_name %></strong>
        <span class="text-muted"><%= "прокомментировал #{message.created_at.to_date != Time.now.to_date ?
         message.created_at.strftime("%d %b %Y") : "в " + message.created_at.strftime("%H:%M")}".squish %></span>
        <% if message.user == current_user%>
          <span class="glyphicon glyphicon-pencil pull-right"></span>
        <% end %>
      </div>
      <div class="panel-body">

          <%= message.text %>

        <%= hidden_field_tag 'message-id-field', message.id.to_s %>
      </div>
    </div>
  </div>
</div>

app/views/tasks/_message_form.html.erb
<%= simple_form_for Message.new do |f| %>
<%= f.hidden_field :sender_name, value: current_user.full_name %>
<%= f.hidden_field :user_id, value: current_user.id %>
<%= f.hidden_field :task_id, value: @task.id %>
<div class="panel-footer">
    <div class="input-group">
        <input id="btn-input" name="message[text]" class="form-control input-sm" placeholder="Type your message here...">
            <span class="input-group-btn">
                            <button class="btn btn-warning btn-sm" id="btn-chat"> Send</button>  
            </span>
    </div>
 </div>
<% end %>

app/views/tasks/_new_message_form.html.erb
<%= simple_form_for Message.new, remote: true do |f| %>
  <%= f.hidden_field :user_id, value: current_user.id %>
  <%= f.hidden_field :task_id, value: @task.id %>
  <%= f.input :text, input_html: { rows: 4 }, label: false, placeholder: "Текст сообщения", hint: form_hint_for("сообщение") %>
  <%= f.button :submit, 'Отправить' %>
<% end %>

app/views/tasks/_note_form.html.erb
<%= simple_form_for Note.new, remote: true do |f| %>
  <%= f.input :text, input_html: { rows: 4 }, label: false, placeholder: "Текст замечания", hint: form_hint_for("замечание", current_user.submission_form_type) %>
  <%= f.hidden_field :submission_id, value: @submission.id %>
  <%= f.button :submit, "Добавить замечание", class: "btn btn-warning", id: "submit_button", disabled: true %>
<% end %>

app/views/tasks/_tabs_for_form.html.erb
<div class="panel panel-default">
  <div class="panel-heading">
    <ul class="nav nav-tabs form-tabs">
      <li class="active"><a data-toggle="tab" href="#<%= comment %>-form">Редактирование</a></li>
      <li><a data-toggle="tab" href="#<%= comment %>-preview">Предпросмотр</a></li>
      <span style="cursor:pointer; font-size: 1.2em; color:#A9A9A9" class="pull-right glyphicon glyphicon-wrench"></span>
    </ul>
  </div>
  <div class="panel-body">
    <div class="tab-content">
      <div id="<%= comment %>-form" class="tab-pane fade in active">
        <% if comment == "note" %>
          <%= render "note_form" %>
        <% else %>
          <%= render "new_message_form" %>
        <% end %>
      </div>
      <div id="<%= comment %>-preview" class="tab-pane fade">
        <p id="<%= comment %>-preview-text"></p>
      </div>
    </div>
  </div>
</div>

app/views/tasks/index.html.erb
<div class="table-responsive">
  <table class="table table-bordered table-condensed">
    <thead>
      <tr>
        <td align="center"><strong>Фамилия</strong></td>
        <td align="center"><strong></strong></td>
        <% @homeworks.each do |homework| %>
          <td class="separator"></td>
          <td align="center" colspan="<%= homework.problems.count %>"><strong> <%= homework.number %> </strong></td>
        <% end %>
      </tr>
      <tr>
        <td></td>
        <td></td>
        <% @problems.each do |problem| %>
          <% if problem.number == 1 %>
            <td class="separator"></td> 
          <% end %>

          <td align="center">  
            <%= problem.number %>
          </td>
        <% end %>
      </tr>
    </thead>

    <% @students.each do |student| %>
      <tr> 
        <td> <%= student.surname %> <%= student.name.first %>. </td>
        <td> <%= student.tasks.select{ |x| x.status != "accepted" }.count %> </td>

        <% student.tasks.each do |task| %>
          <% if task.problem.number == 1 %>
            <td class="separator"></td> 
          <% end %>

          <% case task.status 
              when "accepted" %>
              <td class="accepted"></td>
              <% when "not_accepted" %>
              <td class="not_accepted"></td>
              <% when "not_submitted" %>
              <td></td>
              <% when "accepted_partially" %>
              <td class="accepted_partially"></td>
          <% end %>
        <% end %>

      </tr>
    <% end %>
    
  </table>
</div>

app/views/tasks/show.html.erb
<div class="col-md-8">
  <p>
    <%= link_to 'Назад к курсу', @course %>
  </p>
</div>
<div class="col-md-8">
  <h2 id="task_title">
    <div id="text">
    <% if @task.accepted? %>
      <span class="glyphicon glyphicon-ok-sign"></span>
    <% elsif @task.accepted_partially? %>
      <span class="glyphicon glyphicon-exclamation-sign"></span>
    <% end %>

    Задача <%= @task.name %>

    </div>
  </h2>
</div>

<div class="col-md-4">
  <% if @is_teacher %>
  <h4 align="right">
    <%= @student.full_name %> <br>
    <%= mail_to @student.user.email, @student.user.email %>
  </h4>
  <% end %>
</div>
<div class="col-md-8">
  <div class="col-md-8">
    <div class="row"><div class="well well-small"> <%= markdown(@task.problem.text) %> </div></div>
  </div>
  <div class="col-md-7">
    <% if @is_student && @task.status != "accepted" %>
      <%= link_to "Добавить решение", new_submission_path(problem_id: @task.problem_id, task_id: @task.id), class: "btn btn-primary" %>
    <% end %>

    <% if @task.submissions.any? %>
      <div id="notes" <%= 'style="display: none"'.html_safe unless @task.notes.any? %>>
        <h3> Замечания </h3>
        <%= render @task.notes.reverse %>
      </div>
    <% end %>

    <% if @is_teacher %>
      <% if @task.accepted? %>
        <div class="btn-group">
          <%= link_to "Принято", '#', class: "btn btn-success", disabled: true %>
            <%= link_to "Отменить", task_path(@task, task: {status: after_cancel_status(@task)}), method: :put, class: "btn btn-default" %>
        </div>
      <% else %>
        <% if @task.submissions.any? %>
          <%= render 'note_form' %>
        <% end %>
        <br>

        <%= link_to "Принять", task_path(@task, task: {status: "accepted"}), method: :put, class: "btn btn-success" %>
        <%= link_to "Принять частично", task_path(@task, task: {status: "accepted_partially"}), method: :put, class: "btn btn-warning" %>
      <% end %>
      
    <% end %>

    <% if signed_in? %>
      <%= link_to(@chat_button_title, switch_chat_task_path(@task), class: "btn btn-default", id: "chat-button", remote: true) %>
    <% end %>
    <br><br>

    <% if @task.submissions.any? %>
      <h3>Решения</h3>
        <% @task.submissions.each do |submission| %>
          <h5>
            <div class="btn-group">
              <%= link_to submission.file.url, class: "btn btn-default", disabled: (not submission.file?) do %>
                <span class="glyphicon glyphicon-cloud-download"></span> <%= "v.#{submission.version}" %>
              <% end %>
              <% unless (not submission.url) || (submission.url.empty?) %>
                <%= link_to submission.url, class: "btn btn-default" do %>
                  <span class="glyphicon glyphicon-link"></span> <%= submission.pull_request? ? "Pull request" : URI(submission.url).host %>
                <% end %>
              <% end %>
            </div>
            <%= submission.text %>

            <small><%= submission.created_at.strftime("%H:%M %d.%m.%y") %></small>
          </h5>

        <% end %>
    <% end %>
  </div>


  <div class="col-md-7">
    <br> <br>
    <% if @is_chat_shown %>
      <div id="chat-id" style="display:block"> <%= render 'chat' %> </div>
    <% else %>
      <div id="chat-id" style="display:none"></div>
    <% end %>
  </div>
</div>

app/views/tasks/switch_chat.js.erb
$('#chat-id').html("<%= escape_javascript(render 'chat') %>");
$('#chat-id').slideToggle("fast");

var chat_on = $('#chat-button').text() == 'Показать чат'
if (chat_on)
{
  $('#chat-button').text('Скрыть чат');
  $('html, body').animate({
          scrollTop: $("#new_message").offset().top
      }, 500);
}
else
{
  $('#chat-button').text('Показать чат');
}