config/routes.rb
Rails.application.routes.draw do

  root 'welcome#index'

  devise_for :users, controllers: { registrations: 'registrations', omniauth_callbacks: 'omniauth_callbacks' }

  get 'courses/:id/terms/:term_number', to: 'courses#show', as: "show_term"
  put 'courses/:id/terms/new', to: 'courses#add_term', as: "add_term"
  get 'courses/:id/statistics', to: 'courses#statistics', as: "show_statistics"
  put 'courses/:id/terms/delete_last', to: 'courses#delete_term', as: "delete_term"
  # GitHub Authorization callback
  get 'github/callback'
  # Webhooks url
  post 'github/payload'

  resources :courses
  resources :students
  resources :homeworks

  resources :invitations, only: [ :new, :create, :edit, :update ]
  resources :tasks, only: [ :show, :update ] { member { get 'switch_chat' } }

  resources :messages
  
  resources :submissions, only: [ :new, :create, :index, :update ]
  resources :problems, only: [ :show ]
  resources :notes
  resources :links
  resources :notifications, only: [:update]
end

app/controllers/courses_controller.rb
class CoursesController < ApplicationController
  include Markdown
  include ErrorsHelper
  include PermissionsHelper
  helper_method :markdown

  before_action :set_course, only: [ :edit, :show, :update, :add_term, :delete_term, :destroy, :statistics ]
  before_action :check_edit_permissions, only: [ :edit, :update, :add_term, :delete_term, :destroy ]

  def new
    @course = Course.new
  end

  def create
    @course = Course.create(course_params.merge(teacher_id: current_user.id))
    if @course.valid?
      @course.terms.create()
      redirect_to @course
    else
      render "new"
    end
  end

  def show
    @terms = @course.terms.reverse

    if params[:term_number]
      @term = @course.terms.find_by number: params[:term_number]
    else
      @term = @course.terms.last
    end
    raise ActionController::RoutingError.new 'Not Found' if @term.nil?

    @teacher_id = @course.teacher_id

    if signed_in? && current_user.id == @teacher_id
      @teacher = true
      @students = @term.students.where(active: true).includes(jobs: :tasks)
    else
      @students = @term.students.where(approved: true).includes(jobs: :tasks)
    end

    if signed_in? && current_user.student?
      @student = @term.students.find_by user: current_user
    end

    @tasks = @student.tasks if @student

    @tasks_left = 0
    @students.each do |student|
      @tasks_left += student.tasks_left_count
    end

    @assignments = @term.assignments.order(:id).includes(:problems)
  end

  def statistics
    @terms = @course.terms
    @teacher_id = @course.teacher_id
    @statistics = true

    if signed_in?
      if current_user.id == @teacher_id
        @teacher = true
      elsif current_user.student?
        @student = Student.where(approved: true,  user_id: current_user, term: @terms).any?
      end
    end

    @notes_number = @course.notes_number_hash
    @notes_total = @notes_number.values.sum

    @first_try_accepted_tasks_number = @course.first_try_accepted_tasks_number_hash
    @first_try_accepted_tasks_total = @first_try_accepted_tasks_number.values.sum
  end

  def index
    @courses = Course.all_hash
  end

  def edit
  end

  def update
    @course.update(course_params)
    redirect_to @course
  end

  def add_term # todo rewrite with ajax
    @course.terms.create()

    redirect_to :back
  end

  def delete_term
    @course.terms.last.destroy
    redirect_to @course
  end

  def destroy
    @course.destroy
    redirect_to courses_path
  end

  private
  def course_params
    params.require(:course).permit(:group_name, :name, :active)
  end

  def set_course
    @course = Course.find(params[:id])
  end

  def check_edit_permissions
    Errors.forbidden(self) unless
        Permissions.has_edit_course_permissions?(current_user, @course)
  end
end

app/helpers/courses_helper.rb
module CoursesHelper
end

app/views/courses/_colouring_legend.html.erb
<a style="padding: 10px 4px 4px 4px " data-placement="bottom" data-toggle="popover" data-trigger="hover" data-container="body" data-placement="right" type="button" data-html="true" href="#" id="legend">
    <span style="font-size: 16px;" class="glyphicon glyphicon-question-sign" aria-hidden="true"></span>
</a>
<div id="popover-content" class="hide">
  <ul class="list-group">
    <li class="list-group-item task-with-submissions">Загружено решение</li>
    <li class="list-group-item task-with-notes">Есть замечания</li>
    <li class="list-group-item task-with-new-submissions-and-notes">Загружено новое решение</li>
    <li class="list-group-item accepted-task">Решение принято</li>
  </ul>
</div>

<script type="text/javascript">
$("[data-toggle=popover]").popover({
    html: true, 
    content:
        function() {
          return $('#popover-content').html();
        }
});
</script> 

app/views/courses/_course_info.html.erb
<div class="row">
  <div class="col-md-8 page-heading">
    <h1> <%= @course.name %> </h1>
    <h3>
      <%= "#{@course.group_name} группа" %>
      <% if @teacher %>
        <%= link_to edit_course_path(@course) do %>
          <span class="glyphicon glyphicon-pencil"></span>
        <% end %>
      <% end %>
    </h3>
    <% if !@statistics %>
      <%= render 'not_approved_label' %>
    <% end %>
  </div>

  <div class="col-md-4" align="right">
    <% if !@teacher %>
      <h3> <%= @course.teacher.full_name %> </h3>
      <h3>
        <% if @student %>
          <%= mail_to @course.teacher.email do %>
            <%= @course.teacher.email %>
          <% end %>
        <% end %>
      </h3>
    <% else %>
      <%= render 'management_button' %>
    <% end %>
    <% if !@statistics %>
      <% if !@student || (@student && !@student.active?) %>
        <%= render 'enroll_button' %>
      <% elsif @student && @student.approved? %>
        <%= render 'unsubscribe_button' %>
      <% end %>
    <% end %>
  </div>
</div>

app/views/courses/_course_settings.html.erb
<div class="row">
	<div class="col-md-12">
    <h5 align="right">
	      <%= link_to "Настройки курса", settings_course_path(@course.id), class: 'glyphicon glyphicon-cog' %>
	  </h5>
	</div>
</div>

app/views/courses/_enroll_button.html.erb
<% if signed_in? && current_user.student? %>
  <% if @student.nil? %>
    <%= link_to 'Записаться', students_path(student: {term_id: @term.id}), method: :post, class: 'btn btn-success' %>
  <% else %>
    <%= link_to 'Записаться', student_path(@student, student: { active: true }), method: :put, class: 'btn btn-success' %>
  <% end %>
<% end %>

app/views/courses/_form.html.erb
<%= simple_form_for @course do |f| %>
  <div class="col-md-4">
    <%= f.input :group_name, label: 'Номер группы' %>
    <%= f.input :name, label: 'Предмет' %>
    <%= f.button :submit, 'Сохранить', class: 'btn btn-primary' %>
  </div>
<% end %>

app/views/courses/_index.html.erb
<div class="row">
  <div class="col-md-12">
    <ul class="nav nav-tabs" role="tablist">
      <li class="active">
        <a data-toggle="tab" href="#active">Текущие курсы</a>
      </li>
      <li>
        <a data-toggle="tab" href="#finished">Завершённые курсы</a>
      </li>
    </ul>
  </div>
</div>
<br/>
<div class="row">
  <div class="col-md-12">
    <div class="tab-content">
      <div id="active" class="tab-pane fade in active">
        <%= render 'courses/courses', { courses: @courses[:active] } %>
      </div>
      <div id="finished" class="tab-pane fade">
        <%= render 'courses/courses', { courses: @courses[:finished] } %>
      </div>
    </div>
  </div>
</div>

app/views/courses/_not_approved_label.html.erb
<% if @student && @student.active? && (not @student.approved?) %>
      <div class="alert alert-warning" role="alert">
        Преподаватель должен подтвердить Вашу запись.
      </div>
<% end %>

app/views/courses/_statistics.html.erb
<%= render 'course_info' %>

<div class="row">
  <div class="col-md-12">
    <ul class="nav nav-tabs" role="tablist">
      <% @terms.each do |term| %>
        <li><%= link_to "#{term.number} #{browser.mobile? ? "сем." : "семестр"}", show_term_path(@course.id, term.number), remote: true %></li>
      <% end %>
      <li> <%= link_to "Добавить семестр", add_term_path(@course.id), method: :put if @teacher %> </li>
      <li class="active pull-right"> <%= link_to "Статистика", show_statistics_path, remote: true %> </li>
    </ul>
  </div>
</div>

<div class="table-responsive">
  <table class="table table-bordered table-condensed">
    <thead>
      <tr>
        <td align="center"><strong> <%= "Статистика" %> </strong></td>
        <td class="separator"></td>

        <td align="center"><strong> <%= "Всего" %> </strong></td>

        <% @terms.each do |term| %>
          <td align="center"><strong> <%= "#{term.number} семестр" %> </strong></td>
        <% end %>
      </tr>
    </thead>

  <%= render 'statistics_row', row_name: "Комментариев к задачам", data: @notes %>
  <%= render 'statistics_row', row_name: "Сдано задач с первого раза", 
                                   data: @first_try_accepted_tasks %>
  <%= render 'statistics_row', row_name: "Сдано задач", data: @accepted_tasks %>
  <%= render 'statistics_row', row_name: "Попыток сдать задачи", data: @tries_to_pass_task %>
  <%= render 'statistics_row', row_name: "Максимум попыток сдать задачу", 
                                   data: @max_tries_to_pass_task %>
  <%= render 'statistics_row', row_name: "Максимум попыток сдать задачу среди всех студентов",
                               data: @max_tries_to_pass_problem %>
  </table>
</div>

app/views/courses/_statistics_row.html.erb
<tr>
  <td><%= row_name %></td>
  <td class="separator"></td>
  <td align="center"><%= data[:total] %></td>
  <% @terms.each do |term| %>
    <td align="center"><%= data[:number][term] %></td>
  <% end %>
</tr>

app/views/courses/_unsubscribe_button.html.erb
<% if signed_in? && current_user.student? && @student.approved? %>
  <%= link_to student_path(@student, student: { approved: false, active: false }), method: :put, data: { confirm: "Вы уверены, что хотите покинуть курс?" } do %>
    <span class="btn btn-default">Отписаться</span>
  <% end %>
<% end %>

app/views/courses/edit.html.erb
<%= render 'form' %>

app/views/courses/new.html.erb
<%= simple_form_for @course do |f| %>
  <%= f.input :group_name, label: 'Номер группы' %>
  <%= f.input :name, label: 'Предмет' %>
  <%= f.button :submit, 'Добавить курс', class: 'btn btn-primary' %>
<% end %>

app/views/courses/show.html.erb
<%= render 'course_info' %>

<div class="row">
  <div class="col-md-12">
    <%= render 'tabs' %>
    <%= render 'term' %>
  </div>
</div>

app/views/courses/statistics.html.erb
<%= render 'course_info' %>

<div class="row">
  <div class="col-md-12">
    <%= render 'tabs' %>
  </div>
</div>

<div class="table-responsive">
  <table class="table table-bordered table-condensed">
    <thead>
      <tr>
        <td align="center"><strong> <%= "Статистика" %> </strong></td>
        <td class="separator"></td>

        <td align="center"><strong> <%= "Все семестры" %> </strong></td>

        <% @terms.each do |term| %>
          <td align="center"><strong> <%= "#{term.number} семестр" %> </strong></td>
        <% end %>
      </tr>
    </thead>

  <%= statistics_line("Комментариев к задачам", @notes, @notes_total) %>

  <%= statistics_line("Принято задач", @accepted_tasks, @accepted_tasks_total) %>

  <%= statistics_line("Сдано с первого раза", @first_try_accepted_tasks, @first_try_accepted_tasks_total) %>

  <%= statistics_line("Попыток сдать задачи", @attempts_to_pass, @attempts_to_pass_total) %>

  <%= statistics_line("Максимальное число попыток сдать одну задачу ", @max_attempts, @max_attempts_total) %>

  <%= statistics_line("Задача с минимальным количеством попыток", @problems_with_min_attempts_to_pass, '') %>

  <%= statistics_line("Задача с максимальным количеством попыток", @problems_with_max_attempts_to_pass, '') %>

  </table>
</div>